import { Catalogue } from "@quicktalog/common";
import { getCurrencySymbol } from "@/helpers/client";
import { CookiePreferences, Currency } from "@/types";
import { ILinkItem } from "@/types/components";

export const defaultCookiePreferences: CookiePreferences = {
	accepted: false,
	essential: true,
	analytics: false,
	marketing: false,
	timestamp: new Date().toISOString(),
	version: "1.1",
};

export const COOKIE_KEY = "cookiePreferences";

export const KEYWORDS = [
	"digital catalog",
	"online catalog maker",
	"catalog template",
	"free online maker",
	"price list",
	"interactive catalog",
	"mobile-friendly catalog",
	"QR code sharing",
	"AI-powered creation",
	"OCR import",
	"catalog templates",
	"real-time analytics",
	"business catalog",
	"service catalog",
	"product showcase",
	"menu catalog",
	"restaurant menu",
	"beauty salon services",
	"fitness gym classes",
	"café menu",
	"retail products",
	"spa services",
	"electronics catalog",
	"hospitality",
	"no code required",
	"no design skills",
	"instant updates",
	"professional templates",
	"mobile-first design",
	"easy sharing",
	"customer insights",
	"secure platform",
	"free plan",
	"5 minutes setup",
];

export const menuItems: ILinkItem[] = [
	{
		text: "Features",
		url: "#features",
	},
	{
		text: "Pricing",
		url: "#pricing",
	},
	{
		text: "Testimonials",
		url: "#testimonials",
	},
];
export const currencies: Currency[] = [
	{ value: "AED", label: "United Arab Emirates dirham", locale: "ar-AE" },
	{ value: "AFN", label: "Afghan afghani", locale: "fa-AF" },
	{ value: "ALL", label: "Albanian lek", locale: "sq-AL" },
	{ value: "AMD", label: "Armenian dram", locale: "hy-AM" },
	{ value: "ANG", label: "Netherlands Antillean guilder", locale: "nl-CW" },
	{ value: "AOA", label: "Angolan kwanza", locale: "pt-AO" },
	{ value: "ARS", label: "Argentine peso", locale: "es-AR" },
	{ value: "AUD", label: "Australian dollar", locale: "en-AU" },
	{ value: "AWG", label: "Aruban florin", locale: "nl-AW" },
	{ value: "AZN", label: "Azerbaijani manat", locale: "az-AZ" },
	{
		value: "BAM",
		label: "Bosnia and Herzegovina convertible mark",
		locale: "bs-BA",
	},
	{ value: "BBD", label: "Barbados dollar", locale: "en-BB" },
	{ value: "BDT", label: "Bangladeshi taka", locale: "bn-BD" },
	{ value: "BGN", label: "Bulgarian lev", locale: "bg-BG" },
	{ value: "BHD", label: "Bahraini dinar", locale: "ar-BH" },
	{ value: "BIF", label: "Burundian franc", locale: "fr-BI" },
	{ value: "BMD", label: "Bermudian dollar", locale: "en-BM" },
	{ value: "BND", label: "Brunei dollar", locale: "ms-BN" },
	{ value: "BOB", label: "Boliviano", locale: "es-BO" },
	{ value: "BRL", label: "Brazilian real", locale: "pt-BR" },
	{ value: "BSD", label: "Bahamian dollar", locale: "en-BS" },
	{ value: "BTN", label: "Bhutanese ngultrum", locale: "dz-BT" },
	{ value: "BWP", label: "Botswana pula", locale: "en-BW" },
	{ value: "BYN", label: "Belarusian ruble", locale: "be-BY" },
	{ value: "BZD", label: "Belize dollar", locale: "en-BZ" },
	{ value: "CAD", label: "Canadian dollar", locale: "en-CA" },
	{ value: "CDF", label: "Congolese franc", locale: "fr-CD" },
	{ value: "CHF", label: "Swiss franc", locale: "de-CH" },
	{ value: "CLP", label: "Chilean peso", locale: "es-CL" },
	{ value: "CNY", label: "Chinese yuan", locale: "zh-CN" },
	{ value: "COP", label: "Colombian peso", locale: "es-CO" },
	{ value: "CRC", label: "Costa Rican colón", locale: "es-CR" },
	{ value: "CUP", label: "Cuban peso", locale: "es-CU" },
	{ value: "CVE", label: "Cape Verdean escudo", locale: "pt-CV" },
	{ value: "CZK", label: "Czech koruna", locale: "cs-CZ" },
	{ value: "DJF", label: "Djiboutian franc", locale: "fr-DJ" },
	{ value: "DKK", label: "Danish krone", locale: "da-DK" },
	{ value: "DOP", label: "Dominican peso", locale: "es-DO" },
	{ value: "DZD", label: "Algerian dinar", locale: "ar-DZ" },
	{ value: "EGP", label: "Egyptian pound", locale: "ar-EG" },
	{ value: "ERN", label: "Eritrean nakfa", locale: "ti-ER" },
	{ value: "ETB", label: "Ethiopian birr", locale: "am-ET" },
	{ value: "EUR", label: "Euro", locale: "fr-FR" },
	{ value: "FJD", label: "Fiji dollar", locale: "en-FJ" },
	{ value: "FKP", label: "Falkland Islands pound", locale: "en-FK" },
	{ value: "GBP", label: "Pound sterling", locale: "en-GB" },
	{ value: "GEL", label: "Georgian lari", locale: "ka-GE" },
	{ value: "GHS", label: "Ghanaian cedi", locale: "en-GH" },
	{ value: "GIP", label: "Gibraltar pound", locale: "en-GI" },
	{ value: "GMD", label: "Gambian dalasi", locale: "en-GM" },
	{ value: "GNF", label: "Guinean franc", locale: "fr-GN" },
	{ value: "GTQ", label: "Guatemalan quetzal", locale: "es-GT" },
	{ value: "GYD", label: "Guyanese dollar", locale: "en-GY" },
	{ value: "HKD", label: "Hong Kong dollar", locale: "zh-HK" },
	{ value: "HNL", label: "Honduran lempira", locale: "es-HN" },
	{ value: "HRK", label: "Croatian kuna", locale: "hr-HR" },
	{ value: "HTG", label: "Haitian gourde", locale: "ht-HT" },
	{ value: "HUF", label: "Hungarian forint", locale: "hu-HU" },
	{ value: "IDR", label: "Indonesian rupiah", locale: "id-ID" },
	{ value: "ILS", label: "Israeli new shekel", locale: "he-IL" },
	{ value: "INR", label: "Indian rupee", locale: "hi-IN" },
	{ value: "IQD", label: "Iraqi dinar", locale: "ar-IQ" },
	{ value: "IRR", label: "Iranian rial", locale: "fa-IR" },
	{ value: "ISK", label: "Icelandic króna", locale: "is-IS" },
	{ value: "JMD", label: "Jamaican dollar", locale: "en-JM" },
	{ value: "JOD", label: "Jordanian dinar", locale: "ar-JO" },
	{ value: "JPY", label: "Japanese yen", locale: "ja-JP" },
	{ value: "KES", label: "Kenyan shilling", locale: "en-KE" },
	{ value: "KGS", label: "Kyrgyzstani som", locale: "ky-KG" },
	{ value: "KHR", label: "Cambodian riel", locale: "km-KH" },
	{ value: "KMF", label: "Comorian franc", locale: "fr-KM" },
	{ value: "KPW", label: "North Korean won", locale: "ko-KP" },
	{ value: "KRW", label: "South Korean won", locale: "ko-KR" },
	{ value: "KWD", label: "Kuwaiti dinar", locale: "ar-KW" },
	{ value: "KYD", label: "Cayman Islands dollar", locale: "en-KY" },
	{ value: "KZT", label: "Kazakhstani tenge", locale: "kk-KZ" },
	{ value: "LAK", label: "Lao kip", locale: "lo-LA" },
	{ value: "LBP", label: "Lebanese pound", locale: "ar-LB" },
	{ value: "LKR", label: "Sri Lankan rupee", locale: "si-LK" },
	{ value: "LRD", label: "Liberian dollar", locale: "en-LR" },
	{ value: "LSL", label: "Lesotho loti", locale: "en-LS" },
	{ value: "LYD", label: "Libyan dinar", locale: "ar-LY" },
	{ value: "MAD", label: "Moroccan dirham", locale: "ar-MA" },
	{ value: "MDL", label: "Moldovan leu", locale: "ro-MD" },
	{ value: "MGA", label: "Malagasy ariary", locale: "mg-MG" },
	{ value: "MKD", label: "Macedonian denar", locale: "mk-MK" },
	{ value: "MMK", label: "Burmese kyat", locale: "my-MM" },
	{ value: "MNT", label: "Mongolian tögrög", locale: "mn-MN" },
	{ value: "MOP", label: "Macanese pataca", locale: "zh-MO" },
	{ value: "MRU", label: "Mauritanian ouguiya", locale: "ar-MR" },
	{ value: "MUR", label: "Mauritian rupee", locale: "en-MU" },
	{ value: "MVR", label: "Maldivian rufiyaa", locale: "dv-MV" },
	{ value: "MWK", label: "Malawian kwacha", locale: "en-MW" },
	{ value: "MXN", label: "Mexican peso", locale: "es-MX" },
	{ value: "MYR", label: "Malaysian ringgit", locale: "ms-MY" },
	{ value: "MZN", label: "Mozambican metical", locale: "pt-MZ" },
	{ value: "NAD", label: "Namibian dollar", locale: "en-NA" },
	{ value: "NGN", label: "Nigerian naira", locale: "en-NG" },
	{ value: "NIO", label: "Nicaraguan córdoba", locale: "es-NI" },
	{ value: "NOK", label: "Norwegian krone", locale: "nb-NO" },
	{ value: "NPR", label: "Nepalese rupee", locale: "ne-NP" },
	{ value: "NZD", label: "New Zealand dollar", locale: "en-NZ" },
	{ value: "OMR", label: "Omani rial", locale: "ar-OM" },
	{ value: "PAB", label: "Panamanian balboa", locale: "es-PA" },
	{ value: "PEN", label: "Peruvian sol", locale: "es-PE" },
	{ value: "PGK", label: "Papua New Guinean kina", locale: "en-PG" },
	{ value: "PHP", label: "Philippine peso", locale: "en-PH" },
	{ value: "PKR", label: "Pakistani rupee", locale: "ur-PK" },
	{ value: "PLN", label: "Polish złoty", locale: "pl-PL" },
	{ value: "PYG", label: "Paraguayan guaraní", locale: "es-PY" },
	{ value: "QAR", label: "Qatari riyal", locale: "ar-QA" },
	{ value: "RON", label: "Romanian leu", locale: "ro-RO" },
	{ value: "RSD", label: "Serbian dinar", locale: "sr-RS" },
	{ value: "RUB", label: "Russian ruble", locale: "ru-RU" },
	{ value: "RWF", label: "Rwandan franc", locale: "fr-RW" },
	{ value: "SAR", label: "Saudi riyal", locale: "ar-SA" },
	{ value: "SBD", label: "Solomon Islands dollar", locale: "en-SB" },
	{ value: "SCR", label: "Seychellois rupee", locale: "en-SC" },
	{ value: "SDG", label: "Sudanese pound", locale: "ar-SD" },
	{ value: "SEK", label: "Swedish krona", locale: "sv-SE" },
	{ value: "SGD", label: "Singapore dollar", locale: "en-SG" },
	{ value: "SHP", label: "Saint Helena pound", locale: "en-SH" },
	{ value: "SLL", label: "Sierra Leonean leone", locale: "en-SL" },
	{ value: "SOS", label: "Somali shilling", locale: "so-SO" },
	{ value: "SRD", label: "Surinamese dollar", locale: "nl-SR" },
	{ value: "SSP", label: "South Sudanese pound", locale: "en-SS" },
	{ value: "STN", label: "São Tomé and Príncipe dobra", locale: "pt-ST" },
	{ value: "SVC", label: "Salvadoran colón", locale: "es-SV" },
	{ value: "SYP", label: "Syrian pound", locale: "ar-SY" },
	{ value: "SZL", label: "Swazi lilangeni", locale: "en-SZ" },
	{ value: "THB", label: "Thai baht", locale: "th-TH" },
	{ value: "TJS", label: "Tajikistani somoni", locale: "tg-TJ" },
	{ value: "TMT", label: "Turkmenistan manat", locale: "tk-TM" },
	{ value: "TND", label: "Tunisian dinar", locale: "ar-TN" },
	{ value: "TOP", label: "Tongan pa'anga", locale: "to-TO" },
	{ value: "TRY", label: "Turkish lira", locale: "tr-TR" },
	{ value: "TTD", label: "Trinidad and Tobago dollar", locale: "en-TT" },
	{ value: "TWD", label: "New Taiwan dollar", locale: "zh-TW" },
	{ value: "TZS", label: "Tanzanian shilling", locale: "sw-TZ" },
	{ value: "UAH", label: "Ukrainian hryvnia", locale: "uk-UA" },
	{ value: "UGX", label: "Ugandan shilling", locale: "en-UG" },
	{ value: "USD", label: "United States dollar", locale: "en-US" },
	{ value: "UYU", label: "Uruguayan peso", locale: "es-UY" },
	{ value: "UZS", label: "Uzbekistani so'm", locale: "uz-UZ" },
	{ value: "VES", label: "Venezuelan bolívar", locale: "es-VE" },
	{ value: "VND", label: "Vietnamese đồng", locale: "vi-VN" },
	{ value: "VUV", label: "Vanuatu vatu", locale: "bi-VU" },
	{ value: "WST", label: "Samoan tālā", locale: "sm-WS" },
	{ value: "XAF", label: "Central African CFA franc", locale: "fr-CM" },
	{ value: "XCD", label: "East Caribbean dollar", locale: "en-AG" },
	{ value: "XOF", label: "West African CFA franc", locale: "fr-BF" },
	{ value: "XPF", label: "CFP franc", locale: "fr-PF" },
	{ value: "YER", label: "Yemeni rial", locale: "ar-YE" },
	{ value: "ZAR", label: "South African rand", locale: "en-ZA" },
	{ value: "ZMW", label: "Zambian kwacha", locale: "en-ZM" },
	{ value: "ZWL", label: "Zimbabwean dollar", locale: "en-ZW" },
].map((c) => ({
	...c,
	symbol: getCurrencySymbol(c.value),
}));

export const contactTypes = [
	{ value: "phone", label: "Phone" },
	{ value: "email", label: "Email" },
	{ value: "instagram", label: "Instagram" },
	{ value: "tiktok", label: "TikTok" },
	{ value: "website", label: "Website" },
	{ value: "facebook", label: "Facebook" },
	{ value: "twitter", label: "Twitter" },
];

export const defaultServiceCatalogueData: Catalogue = {
	name: "",
	status: "draft",
	theme: "",
	logo: "",
	title: "",
	currency: "",
	contact: [],
	subtitle: "",
	services: [
		{
			name: "",
			layout: "variant_1",
			order: 1,
			items: [],
		},
	],
	partners: [],
	legal: {},
	configuration: {},
	id: "",
	created_by: "",
};

export const DEFAULT_LOGO = "/logo.svg";
export const DARK_LOGO = "/logo-light.svg";
