import { PricingPlan } from "@/types"

export const tiers: PricingPlan[] = [
  {
    id: 0,
    name: "Starter",
    priceId: { month: "pri_01k27ajepm199twd1x77rpwdrq", year: "pri_01k27ajepm199twd1x77rpwdrq" },
    description: "Perfect for individuals and small businesses getting started.",
    features: {
      support: "Email support",
      catalogues: 1,
      newsletter: false,
      customization: "Basic",
      ocr_ai_import: 0,
      traffic_limit: 800,
      custom_features: false,
      analytics: "Basic",
      ai_catalogue_generation: 0,
    },
  },
  {
    id: 1,
    name: "Pro",
    priceId: { month: "pri_01k277hdtkkb1xdbz6karkqek9", year: "pri_01k277q6ftcjfzy9v7xhe6ckdt" },
    description: "Ideal for growing businesses with multiple services.",
    features: {
      support: "Email support",
      catalogues: 5,
      newsletter: false,
      customization: "Moderate",
      ocr_ai_import: 0,
      traffic_limit: 4000,
      custom_features: false,
      analytics: "Basic",
      ai_catalogue_generation: 10,
    },
  },
  {
    id: 2,
    name: "Growth",
    priceId: { month: "pri_01k277kkzqz4ef7nc786ssnw6x", year: "pri_01k277r7p899gfn5nn3ne87pww" },
    description: "Built for teams that need advanced features and analytics.",
    features: {
      support: "Email & Chat support",
      catalogues: 25,
      newsletter: true,
      customization: "Advanced",
      ocr_ai_import: 10,
      traffic_limit: 12000,
      custom_features: false,
      analytics: "Advanced",
      ai_catalogue_generation: 20,
    },
  },
  {
    id: 3,
    name: "Premium",
    priceId: { month: "pri_01k277mzp3tgy7n5wvrsa5v0sx", year: "pri_01k277see7qtyq30kc5g3vyqy9" },
    description: "Enterprise-grade solution with unlimited possibilities.",
    features: {
      support: "Priority Support (Email, Chat, Meeting)",
      catalogues: 50,
      newsletter: true,
      customization: "Advanced",
      ocr_ai_import: 30,
      traffic_limit: 32000,
      custom_features: true,
      analytics: "Advanced",
      ai_catalogue_generation: 50,
    },
  },
]
