import type { ThemeDefinition, ThemeKey } from "@/types/theme";

export const THEME_KEYS = [
	"theme-monochrome",
	"theme-elegant",
	"theme-organic",
	"theme-modern",
	"theme-luxury",
	"theme-creative",
	"theme-coffee",
	"theme-winter-light",
	"theme-advent-1",
	"theme-advent-2",
] as const;

export const THEME_COLOR_TOKENS = [
	"background",
	"foreground",
	"heading",
	"text",
	"buttonText",
	"price",
	"primary",
	"secondary",
	"accent",
	"primaryForeground",
	"secondaryForeground",
	"cardBackground",
	"cardText",
	"cardHeading",
	"cardDescription",
	"cardBorder",
	"sectionBackground",
	"sectionBorder",
	"navigationBackground",
	"navigationText",
	"navigationBorder",
	"categoryAccent",
	"categoryBorder",
] as const;

export const DEFAULT_THEME_KEY: ThemeKey = "theme-monochrome";

export const THEMES: Record<ThemeKey, ThemeDefinition> = {
	"theme-monochrome": {
		label: "Monochrome",
		hidden: false,
		decoration: false,
		colors: {
			background: "#f3f3f3",
			foreground: "#000000",
			heading: "#000000",
			text: "#1a1a1a",
			buttonText: "#ffffff",
			price: "#000000",
			primary: "#000000",
			secondary: "#4d4d4d",
			accent: "#e6e6e6",
			primaryForeground: "#ffffff",
			secondaryForeground: "#ffffff",
			cardBackground: "#ffffff",
			cardText: "#1a1a1a",
			cardHeading: "#000000",
			cardDescription: "#333333",
			cardBorder: "#e0e0e0",
			sectionBackground: "#f7f7f7",
			sectionBorder: "#e0e0e0",
			navigationBackground: "#ffffff",
			navigationText: "#000000",
			navigationBorder: "#e0e0e0",
			categoryAccent: "#000000",
			categoryBorder: "#000000",
		},
		categoryGradient: ["#ffffff", "#f3f3f3"],
		categoryShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
	},
	"theme-elegant": {
		label: "Elegant",
		hidden: false,
		decoration: true,
		colors: {
			background: "#121212",
			foreground: "#fafafa",
			heading: "#fafafa",
			text: "#b3b3b3",
			buttonText: "#1a1a1a",
			price: "#00bcd4",
			primary: "#6699cc",
			secondary: "#2c2c2c",
			accent: "#ffd699",
			primaryForeground: "#ffffff",
			secondaryForeground: "#fafafa",
			cardBackground: "#262626",
			cardText: "#e6e6e6",
			cardHeading: "#ffffff",
			cardDescription: "#b3b3b3",
			cardBorder: "#333333",
			sectionBackground: "#262626",
			sectionBorder: "#333333",
			navigationBackground: "#1f1f1f",
			navigationText: "#ffffff",
			navigationBorder: "#404040",
			categoryAccent: "#6699cc",
			categoryBorder: "#6699cc",
		},
		categoryGradient: ["#262626", "#333333"],
		categoryShadow: "0 4px 20px rgba(102, 153, 204, 0.2)",
	},
	"theme-organic": {
		label: "Organic",
		hidden: false,
		decoration: false,
		colors: {
			background: "#f5f3ea",
			foreground: "#354834",
			heading: "#354834",
			text: "#2d3a2a",
			buttonText: "#f5f2de",
			price: "#5d4a28",
			primary: "#5c7453",
			secondary: "#cba463",
			accent: "#aabd6d",
			primaryForeground: "#f5f2de",
			secondaryForeground: "#354834",
			cardBackground: "#f0efe9",
			cardText: "#354834",
			cardHeading: "#486345",
			cardDescription: "#6b4f3a",
			cardBorder: "#e3e0c9",
			sectionBackground: "#f1eedb",
			sectionBorder: "#d3d0ba",
			navigationBackground: "#ffffff",
			navigationText: "#354834",
			navigationBorder: "#5c7453",
			categoryAccent: "#5c7453",
			categoryBorder: "#5c7453",
		},
		categoryGradient: ["#f4f3ec", "#efebc5"],
		categoryShadow: "0 4px 20px rgba(92, 116, 83, 0.15)",
	},
	"theme-modern": {
		label: "Modern",
		hidden: false,
		decoration: false,
		colors: {
			background: "#1a1a2b",
			foreground: "#ffffff",
			heading: "#ffffff",
			text: "#f3f3f3",
			buttonText: "#1a1a1a",
			price: "#ff8fa3",
			primary: "#8b6cb3",
			secondary: "#33334d",
			accent: "#e64676",
			primaryForeground: "#ffffff",
			secondaryForeground: "#ffffff",
			cardBackground: "#2d2d55",
			cardText: "#f2f2f2",
			cardHeading: "#ffffff",
			cardDescription: "#d1d1d1",
			cardBorder: "#404040",
			sectionBackground: "#23233a",
			sectionBorder: "#404040",
			navigationBackground: "#1e1e35",
			navigationText: "#ffffff",
			navigationBorder: "#3a3a5a",
			categoryAccent: "#8b6cb3",
			categoryBorder: "#8b6cb3",
		},
		categoryGradient: ["#23233a", "#2d2d45"],
		categoryShadow: "0 4px 20px rgba(139, 108, 179, 0.2)",
	},
	"theme-luxury": {
		label: "Luxury",
		hidden: false,
		decoration: false,
		colors: {
			background: "#fff8e7",
			foreground: "#1a1a1a",
			heading: "#1a1a1a",
			text: "#080808",
			buttonText: "#1a1a1a",
			price: "#8b6914",
			primary: "#d3af37",
			secondary: "#856d3d",
			accent: "#f0e3b2",
			primaryForeground: "#1a1a1a",
			secondaryForeground: "#ffffff",
			cardBackground: "#ffffff",
			cardText: "#333333",
			cardHeading: "#1a1a1a",
			cardDescription: "#333333",
			cardBorder: "#d9d9d9",
			sectionBackground: "#e6e6e6",
			sectionBorder: "#d9d9d9",
			navigationBackground: "#ffffff",
			navigationText: "#1a1a1a",
			navigationBorder: "#d9d9d9",
			categoryAccent: "#d3af37",
			categoryBorder: "#d3af37",
		},
		categoryGradient: ["#ffffff", "#f8f4e0"],
		categoryShadow: "0 4px 20px rgba(211, 175, 55, 0.15)",
	},
	"theme-creative": {
		label: "Creative",
		hidden: false,
		decoration: false,
		colors: {
			background: "#15161e",
			foreground: "#f8f8f1",
			heading: "#f8f8f1",
			text: "#aab7d4",
			buttonText: "#f8f8f1",
			price: "#ff8fa3",
			primary: "#ff6b6b",
			secondary: "#6b8bff",
			accent: "#ffd166",
			primaryForeground: "#1d1e28",
			secondaryForeground: "#ffffff",
			cardBackground: "#3a3b55",
			cardText: "#f8f8f1",
			cardHeading: "#ffffff",
			cardDescription: "#e8edf5",
			cardBorder: "#3c3d4f",
			sectionBackground: "#2a2b39",
			sectionBorder: "#3c3d4f",
			navigationBackground: "#2a2b39",
			navigationText: "#f8f8f1",
			navigationBorder: "#3c3d4f",
			categoryAccent: "#ff6b6b",
			categoryBorder: "#ff6b6b",
		},
		categoryGradient: ["#2a2b39", "#343545"],
		categoryShadow: "0 4px 20px rgba(255, 107, 107, 0.2)",
	},
	"theme-coffee": {
		label: "Coffee",
		hidden: false,
		decoration: true,
		colors: {
			background: "#f5f0e8",
			foreground: "#2a1f14",
			heading: "#2a1f14",
			text: "#3d2e1f",
			buttonText: "#f5f0e8",
			price: "#6b4c20",
			primary: "#8b6914",
			secondary: "#a0522d",
			accent: "#d4b896",
			primaryForeground: "#f5f0e8",
			secondaryForeground: "#f5f0e8",
			cardBackground: "#faf6ef",
			cardText: "#2a1f14",
			cardHeading: "#2a1f14",
			cardDescription: "#5a3e26",
			cardBorder: "#d9cbb5",
			sectionBackground: "#ede5d4",
			sectionBorder: "#c8b89a",
			navigationBackground: "#faf6ef",
			navigationText: "#2a1f14",
			navigationBorder: "#c8b89a",
			categoryAccent: "#8b6914",
			categoryBorder: "#8b6914",
		},
		categoryGradient: ["#faf6ef", "#ede5d4"],
		categoryShadow: "0 4px 20px rgba(139, 105, 20, 0.15)",
	},
	"theme-winter-light": {
		label: "Winter Light",
		hidden: true,
		decoration: true,
		colors: {
			background: "#f7faff",
			foreground: "#14273e",
			heading: "#14273e",
			text: "#233a57",
			buttonText: "#ffffff",
			price: "#1565c0",
			primary: "#1e88e5",
			secondary: "#e6eef5",
			accent: "#aee4ff",
			primaryForeground: "#ffffff",
			secondaryForeground: "#14273e",
			cardBackground: "#ffffff",
			cardText: "#233a57",
			cardHeading: "#14273e",
			cardDescription: "#355172",
			cardBorder: "#d7e7fb",
			sectionBackground: "#f0f6ff",
			sectionBorder: "#c6dcf5",
			navigationBackground: "#ffffff",
			navigationText: "#14273e",
			navigationBorder: "#d7e7fb",
			categoryAccent: "#aee4ff",
			categoryBorder: "#1e88e5",
		},
		categoryGradient: ["#eaf2ff", "#e4f0ff"],
		categoryShadow: "0 4px 16px rgba(30, 136, 229, 0.12)",
		typography: {
			fontHeading: "var(--font-crimson-text)",
			fontBody: "var(--font-inter)",
			weightHeading: "600",
			weightBody: "400",
			spacingHeading: "-0.015em",
		},
	},
	"theme-advent-1": {
		label: "Advent 1",
		hidden: true,
		decoration: true,
		colors: {
			background: "#7a1d1d",
			foreground: "#fff7f1",
			heading: "#ffe9c6",
			text: "#fff7f1",
			buttonText: "#fffdf9",
			price: "#f5cf9f",
			primary: "#e73b3b",
			secondary: "#c89156",
			accent: "#a59a3a",
			primaryForeground: "#fffdf9",
			secondaryForeground: "#3a0f0f",
			cardBackground: "#933030",
			cardText: "#fff7f1",
			cardHeading: "#ffe9c6",
			cardDescription: "#f2d9c3",
			cardBorder: "#c89156",
			sectionBackground: "#8c2424",
			sectionBorder: "#c89156",
			navigationBackground: "#fffaf5",
			navigationText: "#7a1d1d",
			navigationBorder: "#e7d2bc",
			categoryAccent: "#c89156",
			categoryBorder: "#c89156",
		},
		categoryGradient: ["#933030", "#7a1d1d"],
		categoryShadow: "0 4px 16px rgba(200, 145, 86, 0.15)",
		typography: {
			fontHeading: "var(--font-playfair-display)",
			fontBody: "var(--font-inter)",
			weightHeading: "700",
			weightBody: "400",
			spacingHeading: "-0.02em",
		},
	},
	"theme-advent-2": {
		label: "Advent 2",
		hidden: true,
		decoration: true,
		colors: {
			background: "#29453f",
			foreground: "#f8efe6",
			heading: "#d9c9a3",
			text: "#f8efe6",
			buttonText: "#253630",
			price: "#e3c58f",
			primary: "#e3b67a",
			secondary: "#557b6c",
			accent: "#a1c1af",
			primaryForeground: "#253630",
			secondaryForeground: "#f8efe6",
			cardBackground: "#3b5c53",
			cardText: "#f8efe6",
			cardHeading: "#e3c58f",
			cardDescription: "#ecdfcc",
			cardBorder: "#89a494",
			sectionBackground: "#3b5c53",
			sectionBorder: "#cfa86a",
			navigationBackground: "#f6efe6",
			navigationText: "#2e4a42",
			navigationBorder: "#e3b67a",
			categoryAccent: "#a1c1af",
			categoryBorder: "#e3b67a",
		},
		categoryGradient: ["#3b5c53", "#29453f"],
		categoryShadow: "0 4px 16px rgba(200, 150, 86, 0.1)",
		typography: {
			fontHeading: "var(--font-playfair-display)",
			fontBody: "var(--font-inter)",
			weightHeading: "700",
			weightBody: "400",
			spacingHeading: "-0.02em",
		},
	},
};
